### ISSUE TITLE
Micro tasks

### ISSUE THREAD

**Issue by ZeroEkkusu** [onbjerg/foundry-book#21]
Any small inconsistencies I've noticed, which anyone can fix:
- [x] add example for [`getCode` cheatcode](https://github.com/onbjerg/foundry-book/blob/master/src/reference/cheatcodes.md#getcode)
- [x] add example for [`ffi` cheatcode](https://github.com/onbjerg/foundry-book/blob/master/src/reference/cheatcodes.md#ffi)
- [x] beautify [`prank` cheatcode example](https://github.com/onbjerg/foundry-book/blob/master/src/reference/cheatcodes.md#prank) and add `##### Example` heading
- [ ] clarify or simplify [`expectCall` cheatcode example](https://github.com/onbjerg/foundry-book/blob/master/src/reference/cheatcodes.md#example-10)
- [x] fix errors at [the begging of `ds-test.md`](https://github.com/onbjerg/foundry-book/blob/master/src/reference/ds-test.md#ds-test-reference)
- [x] make [examples in `writing-tests.md`](https://github.com/onbjerg/foundry-book/blob/master/src/forge/writing-tests.md) consistent
- [x] beautify [`cheatcodes.md`](https://github.com/onbjerg/foundry-book/blob/master/src/reference/cheatcodes.md) to be cleaner and easier to read and navigate
- [x] fix [the look (style) of `ds-test.md`](https://github.com/onbjerg/foundry-book/blob/master/src/reference/ds-test.md)
- [ ] reorder cheatcodes in the reference docs? see [this comment](https://github.com/onbjerg/foundry-book/issues/21#issuecomment-1060867469)

**Comment by Sabnock01** [comment]
Seems like a good idea for the cheatcodes would be putting them in alphabetical order?

**Comment by onbjerg** [comment]
Current order is just a mix of what was added first and sometimes a "logical" grouping. I don't have strong opinions about it but I lean towards logical groupings, e.g. cheatcodes that do something externally (`getCode`, `ffi`), cheatcodes that change the runner environment (`prank`, `roll`, `warp`, `fee`, ...) and so on

**Comment by ZeroEkkusu** [comment]
Btw they are documented in the order of this commonly used hevm interface:
https://github.com/brockelmore/forge-std/blob/4aa8f014bd2ef6df9a96f1fa1cedb3e0dda6f901/src/Vm.sol

**Comment by onbjerg** [comment]
Yeah, I should have clarified: the order is from the file @ZeroEkkusu linked, but that order is based on my original comment :smile:
