### ISSUE TITLE
Chapters on current features

### ISSUE THREAD

**Issue by onbjerg** [onbjerg/foundry-book#4]
Meta

- [x] Introduction

Getting started

- [x] Installation
- [x] First steps with Foundry

Forge

- [x] Creating a new project
- [x] Working on an existing project
- [x] Dependencies
  - [x] Add sections on `forge remove` and `forge update`
  - [x] Document release/tag behavior
- [x] Project layout
- [x] foundry.toml
- [x] Tests
  - [x] Writing tests
  - [x] Cheatcodes
  - [x] Understanding traces
- [x] Advanced Testing
  - [x] Fuzz testing
- [x] Continous integration
- [x] Debugger
- [x] Cache
- [x] Deployment (as of now, `forge create`)

Additional guides

- [ ] Incremental adoption
- [x] Integrating with VSCode
- [x] Shell autocompletion

Reference

- [x] `ds-test` Reference
- [x] `foundry.toml` Reference
- [x] Cheatcodes Reference

**Comment by onbjerg** [comment]
I need to find a new example for the fuzz testing, don't want to rip it directly from DappTools.

Some ideas:

- Sorting: conveys the idea, but how often do you write sorts in Solidity?

**Comment by codingnirvana** [comment]
What do you think about the `hasDuplicate` example [here](https://blog.trailofbits.com/2020/08/17/using-echidna-to-test-a-smart-contract-library/)? Testing this code using fuzzing in Forge throws an Arithmetic Underflow/Overflow error.
